# Generated by Django 4.2.3 on 2023-09-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='type_holiday',
            field=models.CharField(blank=True, null=True, verbose_name='Тип отпуск'),
        ),
    ]
