# Generated by Django 4.2.3 on 2023-09-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_holiday_type_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидании'), ('approved', 'Одобренный'), ('cancelled', 'Отменено')], default='waiting', max_length=10, verbose_name='Тип паспорта'),
        ),
    ]
