# Generated by Django 4.2.3 on 2023-08-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_first_name_alter_client_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
    ]
