# Generated by Django 4.2.3 on 2023-09-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_holiday_type_holiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['-id'], 'verbose_name': 'Отпуск', 'verbose_name_plural': 'Отпуск'},
        ),
        migrations.AddField(
            model_name='sickleave',
            name='type_sick',
            field=models.CharField(blank=True, choices=[('Больничный по беременности и родам', 'Больничный по беременности и родам'), ('Больничный по болезни', 'Больничный по болезни')], null=True, verbose_name='Тип Больничный'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидании'), ('approved', 'Одобренный'), ('cancelled', 'Отменено')], default='waiting', max_length=10, verbose_name='Статус'),
        ),
    ]
