# Generated by Django 4.2.3 on 2023-08-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=255, verbose_name='ФИО')),
                ('image', models.ImageField(upload_to='employer/', verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
