# Generated by Django 4.2.3 on 2023-08-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_employer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Лучший Сотрудник', 'verbose_name_plural': 'Лучшие Сотрудники'},
        ),
        migrations.AddField(
            model_name='document',
            name='response_msg',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ответное сообщение'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл'),
        ),
    ]
