# Generated by Django 4.2.3 on 2023-08-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_employer_options_document_response_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_user_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='response_msg',
            field=models.TextField(blank=True, null=True, verbose_name='Ответное сообщение'),
        ),
    ]
