# Generated by Django 4.2.3 on 2023-08-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_client_full_name_client_telegram_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
