# Generated by Django 4.2.3 on 2023-08-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_client_full_name_sickleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_sick_leave',
            field=models.BooleanField(default=False, verbose_name='больничный'),
        ),
    ]
