# Generated by Django 4.2.3 on 2023-08-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_document_is_sick_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sickleave',
            name='data',
        ),
        migrations.AddField(
            model_name='sickleave',
            name='date',
            field=models.CharField(blank=True, default='', verbose_name='Дата больничного'),
        ),
    ]
