# Generated by Django 4.2.4 on 2023-08-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_document_is_sick_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='holiday_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество выходных'),
        ),
    ]
