# Generated by Django 4.2.3 on 2023-08-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_sickleave_data_sickleave_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='holiday_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество выходных'),
        ),
    ]
