# Generated by Django 4.2.3 on 2023-08-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_client_holiday_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобренный'),
        ),
    ]
